services:
  db:
    image: postgres:latest
    container_name: cae_exercices_fiche2_db
    environment:
      POSTGRES_DB: cae_db
      POSTGRES_USER: cae_user
      POSTGRES_PASSWORD: cae
    ports:
      - "5433:5432"